/**
 * The bundled corpus (§9.1) — one static file, no backend, no query layer.
 * Filtering a flat array by overlap and sorting is well under a millisecond,
 * so it can re-run per frame.
 *
 * Generated by `node scripts/build-corpus.mjs` from `scripts/corpus-source.mjs`.
 * Edit the source list, not this import.
 */

import raw from './corpus.json'
import type { CorpusEvent } from '../model/types'

export const CORPUS = raw.events as CorpusEvent[]
export const CORPUS_SCHEMA = raw.schema
